#!/usr/bin/python3
from sys import argv

with open(argv[1]) as f:
    for line in f:
        digit = int(line)
        print("{:d}=".format(digit), end='')
        if digit % 2 == 0:
            print("{}*2".format(digit//2))
            continue
        for i in range(3, digit, 2):
            if digit % i == 0:
                factor = digit//i
                for j in range(3, factor, 2):
                    if factor % j == 0 or j == 0:
                        break
                print("{}*{}".format(factor, i))
                break
